apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJoYW1pZGVzbWIiLCJwYXNzd29yZCI6ImhhbWlkZXNtYjIwMjUiLCJlbWFpbCI6ImhhbWlkLmVzbWJAeWFob28uY29tIiwiYXV0aCI6ImFHRnRhV1JsYzIxaU9taGhiV2xrWlhOdFlqSXdNalU9In19fQ==
kind: Secret
metadata:
  name: todo-app-secret
type: kubernetes.io/dockerconfigjson
